### ISSUE TITLE
"TypeError: fullData is undefined"

### ISSUE THREAD

**Issue by echo66** [plotly/react-plotly.js-editor#185]
Greetings!

I was trying to run the example "simple" and, when I pointed my browser to localhost:3000, I got the following error:

``
The above error occurred in the <TraceConnectedFold> component:
    in TraceConnectedFold (created by TraceAccordion)
    in div (created by TraceAccordion)
    in TraceAccordion (created by DefaultEditor)
    in div (created by Panel)
    in Panel (created by DefaultEditor)
    in div (created by PanelsWithSidebar)
    in PanelsWithSidebar (created by DefaultEditor)
    in DefaultEditor (created by LocalizedComponent)
    in LocalizedComponent (created by PlotlyEditor)
    in div (created by PlotlyEditor)
    in PlotlyEditor (at App.js:54)
    in div (at App.js:53)
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
index:2177
TypeError: fullData is undefined
[Learn More]
``

**Comment by VeraZab** [comment]
Hello! Thanks for trying out the app. 
We're still in pre-release and will be updating this repository frequently. The reason it's not working is because we've published a 0.2.0-alpha.1 version that the package.json of the simple app doesn't pick up as the version's set to ^0.1.0. We're going to make the adjustment in a bit.

In the meantime, if you change the package.json of the app to be `"react-plotly.js-editor": "0.2.0-alpha.1"` you should see the app working.

**Comment by VeraZab** [comment]
we've just updated master with the correct version of react-plotly.js-editor for examples, closing this, thanks for reporting
