### ISSUE TITLE
make sure long lines of text are handled well in editor

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-plotly.js-editor#189]
@aulneau during our discussions for localization, it came up that we've got to make sure that our widgets can handle super long descriptions (ex. german words can be super long) have to make sure the editor can properly wrap long lines of text. Would you verify this when you're checking up on our css?

**Comment by aulneau** [comment]
@VeraZab cool! is localization implemented yet? it'd be great to be able to switch over and see where things could break.

**Comment by VeraZab** [comment]
we've got a stub for it, but it's not fully implemented and the implementation will change once we have more detail, but here's where we mock out our dictionaries:
https://github.com/plotly/react-plotly.js-editor/tree/master/src/locales

**Comment by aulneau** [comment]
![screen shot 2017-12-28 at 11 38 51 am](https://user-images.githubusercontent.com/11803153/34421945-122a57a0-ebd8-11e7-9937-fde13b0209ad.png)

I have also noticed this issue, where the titles are updated when they should probably not contain the actual value. I'll think more about how to solve this. I have been thinking we could add a small tooltip lib like -> https://github.com/ghosh/microtip that would show the full length when you click/hover over a icon... could be '...' or a circle '?'. Will keep thinking on this.

**Comment by bpostlethwaite** [comment]
Oh hey if we are going to add Tooltips I have a request. 

Plotly.js has this big ol' data model that describes all of the possible attributes. Included in that meta information are descriptions for each attribute for example: https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/attributes.js#L82-L89

Because our Editor API knows the exact attribute each field maps to we could show the descriptions in a tooltip when hovering over the Field title! Self documenting UI that is always in sync with Plotly.js. 

So if we add tooltips if the lib could handle this case in the future then that will be :+1:

**Comment by aulneau** [comment]
oh cool sure. Where in the future would those tooltips exist exactly? (still finding my way around)

**Comment by bpostlethwaite** [comment]
Not sure, plotly.js ships a bundle with the descriptions stripped out. Otherwise you can access the meta information with a `Plotly.PlotSchema.getLayoutAttribute(['xaxis', 'title'])` type call. We do this already in the editor to figure things like `min` and `max` from Plotly itself rather then hard coding values that are doomed to fall out of sync.

So the accessors are there and the attribute meta information is there in the Plotly object but the descriptions will likely be stripped out.

**Comment by bpostlethwaite** [comment]
still it is theoretically possible and the plotly.js object contains all the info. Just need to find a way to get a bundle that has the descriptions. Perhaps we can ask users to supply a bundle with descriptions and tooltips will show up. Otherwise they will not. That will work for the ChartStudio.
